In [1]:
import pandas as pd

In [13]:
df = pd.read_excel("planilhas/dados_estruturados.xlsx")
df.head()

,CONTRATO Nº,EMPRESA,SISTEMA,INÍCIO,TÉRMINO,MÊS,VIGÊNCIA,ÍNDICE,PERÍODO DE FATURAMENTO,VALOR PAGO,...,ÍNDICE PUBLICADO,ÍNDICE APLICADO,VALOR REAJUSTADO,VALOR REAJUSTADO\n(POR 12 MESES),PEDIDO/ORDEM DE COMPRAS,STATUS / AÇÃO,DATA DA AÇÃO,DIFERENÇA DE VALOR DE CONTRATO,VALOR PAGO (POR 12 MESES),VALOR REAJUSTADO (POR 12 MESES)
0,17/2022,EMPRESA 278,SISTEMA 01,2024-04-01,2025-04-01,ABRIL,DETERMINADO,IGP-M,MENSAL,879,...,0,0,879.0,879.0000,NÃO,CANCELADO,2024-05-01,0.0,NaN,NaN
1,17/2022,EMPRESA 279,SISTEMA 04,2024-04-01,2025-04-01,ABRIL,DETERMINADO,IGP-M,MENSAL,356,...,0,0,356.0,356.0000,NÃO,CANCELADO,2024-05-01,0.0,NaN,NaN
2,18/2019,EMPRESA 278,SISTEMA 03,2024-11-10,2024-11-10,Novembro,Determinado,IPCA,Mensal,100,...,"4,5","4,5",123.5,278.2892,NaN,NaN,2024-11-10,0.0,100.0,123.5
3,18/2019,EMPRESA 278,SISTEMA 03,2024-11-10,2024-11-10,Novembro,Determinado,IPCA,Mensal,100,...,"4,5","4,5",123.5,794.0658,NaN,NaN,2024-11-10,0.0,100.0,123.5
4,18/2019,EMPRESA 278,SISTEMA 03,2024-11-10,2024-11-10,Novembro,Determinado,IPCA,Mensal,100,...,"4,5","4,5",123.5,660.1522,NaN,NaN,2024-11-10,0.0,100.0,123.5